version: '3.0'
services:
  static-files:
    build: .
    volumes:
      # Format: host path : container path
      - ./target:/app/target
    environment:
      CMS_OBJECTSTORE_PASSWORD:
    command: "./static-files.sh"